/**
 * shadcn/ui primitive components — INTERNAL USE ONLY
 *
 * DO NOT export this barrel from the public API (src/index.ts).
 * DO NOT modify these files — they are generated by the shadcn/ui CLI.
 *
 * To upgrade: run `npx shadcn@latest add <component>` and it will
 * overwrite the relevant file here. Wrapper components in src/components/
 * provide the stable public API.
 *
 * @see https://ui.shadcn.com/docs
 */

export { ButtonPrimitive, buttonVariants } from "./button"
export type { ButtonPrimitiveProps } from "./button"
export { TextBoxPrimitive } from "./textbox"
export { Label } from "./label"
export { Checkbox } from "./checkbox"
export { RadioGroup, RadioGroupItem } from "./radio-group"
export { Switch } from "./switch"
export {
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
  SelectScrollUpButton,
  SelectScrollDownButton,
} from "./select"
export { Textarea } from "./textarea"
export { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "./card"
export { Badge, badgeVariants } from "./badge"
export type { BadgeProps } from "./badge"
export { Avatar, AvatarImage, AvatarFallback } from "./avatar"
export {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuGroup,
  DropdownMenuPortal,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuRadioGroup,
} from "./dropdown-menu"
export { Separator } from "./separator"
